# Site
repository: linkarzu/docker-jekyll-resume

favicon: images/favicon2.ico # (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Christian Arzu (linkarzu)
title: Senior Monitoring Engineer
# email: Your email (optional)
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://resume.linkarzu.com
website_title: Resume
# This website2 below doesnt work
# website2: youtube.com/@linkarzu
# website2_title: YouTube

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: christianarzu
github_username: linkarzu
youtube_username: "@linkarzu"
# twitter_username: jekyllrb
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
  - title: Credly
    icon: fas fa-certificate #I updated the icon version in _sass/base.scss to v6.4.0
    url: https://www.credly.com/users/linkarzu/badges
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://res.cloudinary.com/daqwsgmx6/image/upload/v1683578753/Profile%20pics/linkedin.jpg
about_content: | # this will include new lines to allow paragraphs
  ## Skills and interests:
    - I'm highly skilled and experienced in managing and deploying enterprise monitoring solutions, including the setup of integrations between monitoring tools for alerting and paging via PagerDuty or other paging tool
    - I'm familiar with the DevOps model, taking an application from code to a container registry, then to a Helm chart, and finally deploying it to a Kubernetes cluster. Everything managed through CI/CD pipelines, with ArgoCD handling deployments.
    - I have experience with the incident management process, worked as an SRE for LogMeIn for a few years.
    - I have several professional level certifications, including `CKA: Certified Kubernetes Administrator` and `CCNP` by Cisco
    - I'm a huge Neovim fan, macOS is my daily driver, and Debian is my Linux distro of choice for servers.

  <br>
  ## My useful links (clickable):
    - [Online resume -> resume.linkarzu.com](https://resume.linkarzu.com){:target="_blank"}
    - [Personal blog -> linkarzu.com](https://linkarzu.com){:target="_blank"}
    - [YouTube channel -> youtube.com/@linkarzu](https://www.youtube.com/@linkarzu){:target="_blank"}
    - [GitHub profile -> github.com/linkarzu](https://github.com/linkarzu){:target="_blank"}
    - [Linkedin profile -> linkedin.com/in/christianarzu](https://www.linkedin.com/in/christianarzu){:target="_blank"}
    - [Credly profile -> credly.com/users/linkarzu/badges](https://www.credly.com/users/linkarzu/badges){:target="_blank"}

  <br>
  ## A bit more about me:
    - I enjoy spending time in my homelab, I have a 3 node XCP-NG cluster in which I run several VMs, including 3 DNS servers using bind9, a 3 control plane and 3 worker node HA kubernetes cluster, 3 node docker swarm cluster, 3 node glusterfs storage cluster. I run several containers, for example: Traefik as an ingress and for SSL certs, samba server, zabbix server, a registry, databases, apt-cacher-ng and more.
    - I have a Mikrotik router with a dual ISP connection and configured scripts to failover to the backup ISP when the main ISP goes down. Also have a small managed switch in which I configured VLANs, and also have a dedicated separate network for Wi-Fi guests.
    - My journey in the IT world started when I decided to get my Cisco CCNA certification, but I then soon realized that networking is just a small part of the landscape.
    - I love documenting my work, let's say for example I'm learning to deploy a 3 control plane HA kubernetes cluster, I'll document the whole process in case I need to re-do it.
    <div style="page-break-after: always; visibility: hidden"> \pagebreak </div>

# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

# To reduce space between elements I modified _sass/modern-resume-theme.scss
# In the file look for the modifiedRemSpaceSections comment
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Professional Experience
    layout: list
    content:
      - layout: left
        title: GoTo
        sub_title: Senior Monitoring Engineer
        caption: Sept 2022 - Feb 2025 <br> (2 year 5 months)
        link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          - Manage official monitoring tools used across the company. Highly experienced in the administration and deployment of tools such as:  
            - `LogicMonitor` including collectors either on-prem or cloud  
            - `Catchpoint`, including private nodes  
            - `BigPanda`  
            - `PagerDuty` and `Splunk On-Call`, formerly known as `VictorOps`  
            - `Pingdom`, `PingPlotter`, `ThousandEyes`, `AppDynamics`  
            - `Zabbix`, `Uptime Kuma`  
            - `Prometheus` and `VictoriaMetrics` for container monitoring  
          - Monitor SNMP, WMI devices, cloud infrastructure, synthetic tests, alert routing, and alert correlation.  
          - Deploy and maintain necessary infrastructure either on the cloud or on-prem.  
          - Handle vendor contracts, and guide internal users on how to choose the best tool for the job.
          - Provide the monitoring solution (VictoriaMetrics) for other teams to monitor their Kubernetes applications
          - Deploy applications in Kubernetes with helm manifests using a Jenkincs CI/CD pipeline and ArgoCD

      - layout: left
        title: GoTo
        sub_title: Site Reliability Engineer
        caption: Jul 2020 - Sept 2022 <br> (2 years 2 months)
        # link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          - Worked in the `NOC (Network Operations Center)` team ensuring uptime for all the different public-facing products. 
          - Monitor critical alerts across the company to avoid and fix potential issues. 
          - Incident management including status pages.
          - SSL certificate follow-up to avoid expired certs causing downtime.

      - layout: left
        title: GoTo
        sub_title: Field Engineer
        caption: May 2019 - July 2020 <br> (1 year 2 months)
        # link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          - Deployed Jive’s VoIP cloud PBX for enterprise customers. 
          - Configure and troubleshoot various network devices. 
          - Routers, switches (segmentation of networks through VLANs), firewalls and SD-WAN appliances.

      - layout: left
        title: GoTo
        sub_title: Tier 2 tech support
        caption: Sept 2018 - May 2019 <br> (9 months)
        # link: https://www.goto.com
        quote:
        description: | # this will include new lines to allow paragraphs
          - Handled Jive VoIP customer care issues and T1 reps escalations.
          <div style="page-break-after: always; visibility: hidden"> \pagebreak </div>

      # - layout: left
      #   title: World Connection
      #   sub_title: Quality Analyst
      #   caption: Dec 2016 - Sept 2018 <br> (1 year 10 months)
      #   link: https://worldconnection.com
      #   quote:
      #   description: | # this will include new lines to allow paragraphs
      #     - Working for the website Sparefoot.com
      # - layout: left
      #   title: Telus International
      #   sub_title: Google tech support rep
      #   caption: Sept 2014 - May 2015 <br> (9 months)
      #   link: https://www.telusinternational.com
      #   quote:
      #   description: | # this will include new lines to allow paragraphs
      #     - Google Apps for Work in the Email migrations department
  - title: Education
    layout: list
    content:
      - layout: left
        title: Technical Certifications
        sub_title: Certifications
        caption: 2018 - Present
        quote:
        description: | # this will include new lines to allow paragraphs
          - My latest certification is `CKA: Certified Kubernetes Administrator`
          - But over the years, I've acquired other certs from different vendors (`Cisco`, `Juniper`, `Akamai`, etc).
          - Links to some of my certifications:
            - [CKA: Certified Kubernetes Administrator](https://www.credly.com/badges/5c50c596-19c8-4144-aa34-15df59a09c06){:target="_blank"}
            - [CCNP Routing and Switching](https://www.credly.com/badges/e366f67f-effd-4a83-b3f4-5b3e227965a3){:target="_blank"}
            - [My Credly profile](https://www.credly.com/users/linkarzu/badges){:target="_blank"}
      - layout: left
        title: Universidad Mariano Gálvez
        sub_title: Systems engineering
        caption: 2021 - 2025
        quote:
        description: | # this will include new lines to allow paragraphs
          - Learning programming languages like C++, Java and C#.
          - Data structures in C# (linked lists, binary search trees, etc).

# Footer
footer_show_references: true
# references_title: References on request (Override references text)
references_title: 2024

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
